import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {it,expect} from 'vitest';
import {decodeCollisionSnapshot} from '../../packages/core/src/gameplay.js';
const hash=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
function fixture(){const raw=new Uint8Array(100_000).map((_,i)=>i%17),encoded=new Uint8Array(gzipSync(raw));return {raw,encoded,meta:{encoding:'gzip' as const,bytes:encoded.length,sha256:hash(encoded),decodedBytes:raw.length,decodedSha256:hash(raw)}};}
it('decodes exact bytes and snapshots inputs before awaiting',async()=>{const {raw,encoded,meta}=fixture(),pending=decodeCollisionSnapshot(encoded,meta);encoded.fill(0);meta.decodedBytes=1;expect(await pending).toEqual(raw);});
it('rejects encoded or decoded integrity mismatches and declared size overruns',async()=>{const {encoded,meta}=fixture();await expect(decodeCollisionSnapshot(encoded,{...meta,sha256:'0'.repeat(64)})).rejects.toThrow('checksum');await expect(decodeCollisionSnapshot(encoded,{...meta,decodedSha256:'0'.repeat(64)})).rejects.toThrow('checksum');await expect(decodeCollisionSnapshot(encoded,{...meta,decodedBytes:16})).rejects.toThrow('budget');await expect(decodeCollisionSnapshot(encoded,{...meta,decodedBytes:100_001})).rejects.toThrow('length');});
it('rejects truncation, invalid budgets and cancelled requests',async()=>{const {encoded,meta}=fixture();await expect(decodeCollisionSnapshot(encoded.slice(0,-2),meta)).rejects.toThrow('length');const bad=encoded.slice(0,-2);await expect(decodeCollisionSnapshot(bad,{...meta,bytes:bad.length,sha256:hash(bad)})).rejects.toThrow();await expect(decodeCollisionSnapshot(encoded,{...meta,decodedBytes:268435457})).rejects.toThrow('metadata');const controller=new AbortController();controller.abort();await expect(decodeCollisionSnapshot(encoded,meta,controller.signal)).rejects.toThrow();const other=new AbortController(),pending=decodeCollisionSnapshot(encoded,meta,other.signal);other.abort();await expect(pending).rejects.toThrow();});
