import { afterEach, describe, expect, it, vi } from 'vitest';
import type { GeometryManifest } from '../../packages/core/src/geometry/format.js';
import { integratedTerrainMaterial, integratedTerrainTransform, loadTraceProxy, parseTraceProxyManifest,
  terrainTraceObjectId, traceProxyVerticalError, validateTraceProxy } from '../../packages/core/src/geometry/trace-proxy.js';

const source = { kind: 'analytic-heightfield-v1', seed: 1337, tilesPerSide: 4, cellsPerTile: 64, cellSize: 1, triangleCount: 131072 } as const;
const geometry = { source } as GeometryManifest;
const sourceBytes = new TextEncoder().encode(JSON.stringify({ source })).buffer;
async function hash(bytes: ArrayBuffer) { return [...new Uint8Array(await crypto.subtle.digest('SHA-256', bytes))].map(v => v.toString(16).padStart(2, '0')).join(''); }
async function fixture() {
  // Small validation fixture only: production heights are generated by Rust, never here.
  const payload = new ArrayBuffer(37644); const data = new DataView(payload);
  for (let id = 0; id < 1089; id++) {
    data.setFloat32(id * 12, id % 33 - 16, true); data.setFloat32(id * 12 + 4, -1, true);
    data.setFloat32(id * 12 + 8, Math.floor(id / 33) - 16, true);
  }
  for (let cell = 0; cell < 1024; cell++) {
    const a = Math.floor(cell / 32) * 33 + cell % 32; const b = a + 33;
    [a, b, b + 1, a, b + 1, a + 1].forEach((id, i) => data.setUint32(1089 * 12 + (cell * 6 + i) * 4, id, true));
  }
  const json = { format: 'strata-trace-proxy', version: 1, sourceManifestSha256: await hash(sourceBytes), source,
    grid: { cellsPerSide: 32, sourceStep: 8 }, transform: integratedTerrainTransform, material: integratedTerrainMaterial,
    bounds: { min: [-16, -3, -16], max: [16, -0.25, 16] },
    error: { maxVertical: traceProxyVerticalError, measuredMaxVertical: 0.05 },
    mesh: { url: 'trace-proxy.bin', byteLength: 37644, sha256: await hash(payload), vertexCount: 1089, vertexStride: 12, indexCount: 6144, indexFormat: 'uint32' },
  };
  return { json, payload, manifest: parseTraceProxyManifest(json, geometry) };
}
afterEach(() => vi.unstubAllGlobals());

describe('permanently resident terrain tracing sidecar', () => {
  it('loads a complete immutable upward grid with separate local and source-object identities', async () => {
    const { manifest, payload } = await fixture(); const proxy = await validateTraceProxy(manifest, payload, sourceBytes);
    expect(proxy.payloadBytes).toBe(37644); expect(proxy.triangles).toHaveLength(2048);
    let area = 0;
    for (const [id, triangle] of proxy.triangles.entries()) {
      expect(triangle.id).toBe(id); expect(triangle.boxId).toBe(terrainTraceObjectId); expect(triangle.materialId).toBe(5);
      expect(triangle.normal).toEqual([0, 1, 0]);
      area += ((triangle.p1[2] - triangle.p0[2]) * (triangle.p2[0] - triangle.p0[0])
        - (triangle.p1[0] - triangle.p0[0]) * (triangle.p2[2] - triangle.p0[2])) / 2;
    }
    expect(area).toBe(1024); expect(Object.isFrozen(proxy.triangles[0]!.p0)).toBe(true);
    new DataView(payload).setFloat32(4, -2, true);
    expect(proxy.triangles[0]!.p0[1]).toBe(-1);
    expect(integratedTerrainTransform.scale * 11 + integratedTerrainTransform.translation[1]).toBe(-0.25);
  });

  it('rejects different source settings, transforms, materials, budgets and claimed errors', async () => {
    const { json } = await fixture();
    for (const patch of [
      { source: { ...source, seed: 1 } }, { grid: { cellsPerSide: 64, sourceStep: 4 } },
      { transform: { scale: 0.25, translation: [0, -1.625, 0] } },
      { material: { ...integratedTerrainMaterial, metallic: 1 } },
      { mesh: { ...json.mesh, byteLength: 100_000_000 } },
      { mesh: { ...json.mesh, url: 'https://unrelated.invalid/proxy.bin' } },
      { error: { maxVertical: 0.01, measuredMaxVertical: 0.005 } },
      { error: { maxVertical: traceProxyVerticalError, measuredMaxVertical: Infinity } },
      { bounds: { min: [-16, -3, -16], max: [16, 0, 16] } },
    ]) expect(() => parseTraceProxyManifest({ ...json, ...patch }, geometry)).toThrow(/Invalid trace proxy/);
    expect(() => parseTraceProxyManifest(json, { ...geometry, source: { ...source, cellsPerTile: 128 } })).toThrow(/source/);
  });

  it('binds both payload and exact render-manifest byte identity before unpacking', async () => {
    const { manifest, payload } = await fixture();
    await expect(validateTraceProxy(manifest, payload.slice(4), sourceBytes)).rejects.toThrow(/byte length/);
    const corrupt = payload.slice(0); new Uint8Array(corrupt)[1] = 1;
    await expect(validateTraceProxy(manifest, corrupt, sourceBytes)).rejects.toThrow(/SHA-256/);
    await expect(validateTraceProxy(manifest, payload, new TextEncoder().encode(`${new TextDecoder().decode(sourceBytes)}\n`).buffer)).rejects.toThrow(/linkage/);
  });

  it('rejects malformed geometry even when its updated payload hash matches', async () => {
    const { json, payload } = await fixture();
    for (const mutate of [
      (view: DataView) => view.setFloat32(4, NaN, true),
      (view: DataView) => view.setFloat32(4, 0, true),
      (view: DataView) => view.setFloat32(0, -15.5, true),
      (view: DataView) => view.setUint32(1089 * 12 + 4, 999999, true),
      (view: DataView) => view.setUint32(1089 * 12 + 4, 34, true),
    ]) {
      const broken = payload.slice(0); mutate(new DataView(broken));
      const manifest = parseTraceProxyManifest({ ...json, mesh: { ...json.mesh, sha256: await hash(broken) } }, geometry);
      await expect(validateTraceProxy(manifest, broken, sourceBytes)).rejects.toThrow(/vertex|grid|topology/);
    }
  });

  it('uses bounded relative requests and propagates creation abort without fetching pages', async () => {
    const { json, payload } = await fixture(); const requests: string[] = [];
    vi.stubGlobal('fetch', vi.fn(async (input: URL) => {
      requests.push(input.href);
      return input.pathname.endsWith('.json') ? new Response(JSON.stringify(json)) : new Response(payload.slice(0));
    }));
    const url = new URL('https://assets.invalid/courtyard/trace-proxy.json');
    expect((await loadTraceProxy(url, geometry, sourceBytes)).triangles).toHaveLength(2048);
    expect(requests).toEqual([url.href, 'https://assets.invalid/courtyard/trace-proxy.bin']);
    const abort = new AbortController(); abort.abort();
    await expect(loadTraceProxy(url, geometry, sourceBytes, abort.signal)).rejects.toMatchObject({ name: 'AbortError' });
    expect(requests).toHaveLength(2);
    vi.stubGlobal('fetch', vi.fn(async () => new Response('x', { headers: { 'content-length': '9999999' } })));
    await expect(loadTraceProxy(url, geometry, sourceBytes)).rejects.toThrow(/byte budget/);
  });
});
