import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { cookInitializationSource, deferred, removeInitializationSource, type CookedInitializationSource } from './cooked-geometry-initialization.js';

export interface CookedRegionSource extends CookedInitializationSource {
  readonly manifestBytes: Uint8Array<ArrayBuffer>;
}

/** Unchanged production cooker; all generated bytes stay in a dedicated OS temporary directory. */
export async function cookRegionSource(seed: number): Promise<CookedRegionSource> {
  const source = await cookInitializationSource(seed);
  try { return { ...source, manifestBytes: new Uint8Array(await readFile(join(source.directory, 'manifest.json'))) }; }
  catch (cause) { await removeInitializationSource(source); throw cause; }
}

export interface ControlledRegionRequest {
  readonly source: CookedRegionSource;
  readonly kind: 'manifest' | 'page';
  readonly pageId: number | null;
  readonly signal: AbortSignal | null;
  /** Response delivery is distinct from body, digest, cancellation and owner settlement. */
  readonly delivered: boolean;
  respond(options?: { corrupt?: boolean; status?: number }): void;
  respondWithHeldCancellation(): { readonly started: Promise<void>; release(): void };
  reject(reason: Error): void;
}

/** Real manifest/page bytes with manual delivery and deliberately abort-insensitive fetches. */
export function controlledRegionFetch(sources: readonly CookedRegionSource[]) {
  const requests: ControlledRegionRequest[] = [];
  const cancellationReleases = new Set<() => void>();
  const fetchRegions: typeof fetch = async (input, options) => {
    const url = new URL(input instanceof Request ? input.url : String(input));
    const source = sources.find(value => value.url.href === url.href
      || value.manifest.pages.some(page => new URL(page.url, value.url).href === url.href));
    if (!source) throw new Error(`Unexpected region fixture URL: ${url.href}`);
    const kind = source.url.href === url.href ? 'manifest' : 'page';
    const pageId = kind === 'manifest' ? null : source.manifest.pages.findIndex(page => new URL(page.url, source.url).href === url.href);
    const expected = kind === 'manifest' ? source.manifestBytes : source.pages[pageId!]!;
    const response = deferred<Response>();
    let delivered = false;
    const beginDelivery = (): void => {
      if (delivered) throw new Error('Controlled region response delivered twice.');
      delivered = true;
    };
    const request: ControlledRegionRequest = {
      source, kind, pageId, signal: options?.signal ?? null,
      get delivered() { return delivered; },
      respond(settings = {}) {
        beginDelivery();
        const bytes = expected.slice();
        if (settings.corrupt) bytes[0] = bytes[0]! ^ 1;
        const body = new ReadableStream<Uint8Array<ArrayBuffer>>({ start(controller) {
          controller.enqueue(bytes.subarray(0, 173)); controller.enqueue(bytes.subarray(173)); controller.close();
        } });
        response.resolve(new Response(body, { status: settings.status ?? 200, headers: { 'content-length': String(bytes.byteLength) } }));
      },
      respondWithHeldCancellation() {
        beginDelivery();
        const started = deferred<void>(); const canceled = deferred<void>();
        const release = (): void => { canceled.resolve(); cancellationReleases.delete(release); };
        cancellationReleases.add(release);
        response.resolve(new Response(new ReadableStream<Uint8Array<ArrayBuffer>>({
          cancel() { started.resolve(); return canceled.promise; },
        }), { headers: { 'content-length': String(expected.byteLength) } }));
        return { started: started.promise, release };
      },
      reject(reason) { beginDelivery(); response.reject(reason); },
    };
    requests.push(request);
    return response.promise;
  };
  return { fetch: fetchRegions, requests,
    get pending() { return requests.filter(request => !request.delivered); },
    settleForCleanup() {
      for (const request of requests) if (!request.delivered) request.respond();
      for (const release of [...cancellationReleases]) release();
    },
  };
}
